server:
  port: 5050

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: r2dbc:postgresql://data-db:5432/data-db
    username: owner
    password: password

  r2dbc:
    url: r2dbc:postgresql://data-db:5432/data-db
    username: owner
    password: password
